=== BackupTheBerlios/kludge-svn/trunk/kludge.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://kludge.berlios.de/v1/kludge"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns="http://kludge.berlios.de/v1/kludge"
	    elementFormDefault="qualified"
	    attributeFormDefault="unqualified">
 <xsd:element name="kludgeApp" type="KludgeConfig"/>
 
 <xsd:simpleType name="oneDigitOctalInteger">
  <xsd:restriction base="xsd:nonNegativeInteger">
   <xsd:minInclusive value="0"/>
   <xsd:maxInclusive value="7"/>
  </xsd:restriction>
 </xsd:simpleType>
 
 <xsd:simpleType name="eightBitInteger">
  <xsd:restriction base="xsd:nonNegativeInteger">
   <xsd:minInclusive value="00"/>
   <xsd:maxInclusive value="255"/>
  </xsd:restriction>
 </xsd:simpleType>
 
 
 <xsd:complexType name="KludgeFGenType">
  <xsd:sequence>
   <xsd:element name="source" minOccurs="0" maxOccurs="unbounded">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="sink" minOccurs="0" maxOccurs="unbounded">
       <xsd:complexType>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
	<xsd:attribute name="group" type="xsd:string" use="required"/>
       </xsd:complexType>
      </xsd:element>
     </xsd:sequence>
     <xsd:attribute name="name" type="xsd:string" use="required"/>
     <xsd:attribute name="type" type="xsd:string" use="optional"/>
     <xsd:attribute name="freq" type="xsd:double" use="optional"/>
     <xsd:attribute name="phase" type="xsd:double" use="optional"/>  
    </xsd:complexType>
   </xsd:element>
  </xsd:sequence> 
  <xsd:attribute name="name" type="xsd:string" use="required"/>
 </xsd:complexType>

 <xsd:complexType name="ExpertDaqType">
  <xsd:sequence>
   <xsd:element name="source" minOccurs="0" maxOccurs="unbounded">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="sink" minOccurs="0" maxOccurs="unbounded">
       <xsd:complexType>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
	<xsd:attribute name="group" type="xsd:string" use="required"/>
       </xsd:complexType>
      </xsd:element>
     </xsd:sequence>
     <xsd:attribute name="name" type="xsd:string" use="required"/>
     <xsd:attribute name="type" type="xsd:string" use="optional"/>
     <xsd:attribute name="address" type="eightBitInteger" use="required"/>
    </xsd:complexType>
   </xsd:element>
  </xsd:sequence> 
  <xsd:attribute name="name" type="xsd:string" use="required"/>
  <xsd:attribute name="device" type="xsd:string" use="required"/>
  <xsd:attribute name="baudrate" type="xsd:nonNegativeInteger" use="optional"/>
 </xsd:complexType>

 <xsd:complexType name="DumbFileReplayerType">
  <xsd:sequence>
   <xsd:element name="source" minOccurs="0" maxOccurs="unbounded">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="sink" minOccurs="0" maxOccurs="unbounded">
       <xsd:complexType>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
	<xsd:attribute name="group" type="xsd:string" use="required"/>
       </xsd:complexType>
      </xsd:element>
     </xsd:sequence>
     <xsd:attribute name="name" type="xsd:string" use="required"/>
     <xsd:attribute name="data_group" type="xsd:string" use="optional"/>
     <xsd:attribute name="data_source" type="xsd:string" use="optional"/>
     <xsd:attribute name="autorepeat" type="xsd:boolean" use="optional"/>
    </xsd:complexType>
   </xsd:element>
  </xsd:sequence> 
  <xsd:attribute name="name" type="xsd:string" use="required"/>
  <xsd:attribute name="url" type="xsd:string" use="required"/>
 </xsd:complexType>
 
 <xsd:complexType name="KludgeIMapType">
  <xsd:sequence>
   <xsd:element name="sink" minOccurs="0" maxOccurs="unbounded">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="source" minOccurs="0" maxOccurs="unbounded">
       <xsd:complexType>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
	<xsd:attribute name="group" type="xsd:string" use="required"/>
       </xsd:complexType>
      </xsd:element>
     </xsd:sequence>
     <xsd:attribute name="name" type="xsd:string" use="required"/>
     <xsd:attribute name="x" type="xsd:double" use="required"/>
     <xsd:attribute name="y" type="xsd:double" use="required"/>
     <xsd:attribute name="type" type="xsd:string" use="optional"/>
     <xsd:attribute name="data_offset" type="xsd:nonNegativeInteger" use="optional"/>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="image" minOccurs="0" maxOccurs="1">
    <xsd:complexType>
     <xsd:simpleContent>
      <xsd:extension base="xsd:base64Binary">
       <xsd:attribute name="url" type="xsd:string" use="optional"/>
      </xsd:extension> 
     </xsd:simpleContent>
    </xsd:complexType>
   </xsd:element>
  </xsd:sequence> 
  <xsd:attribute name="name" type="xsd:string" use="required"/>
  <xsd:attribute name="colormap" type="xsd:string" use="optional"/>
  <xsd:attribute name="x" type="xsd:double" use="optional"/>
  <xsd:attribute name="y" type="xsd:double" use="optional"/>
  <xsd:attribute name="width" type="xsd:double" use="optional"/>
  <xsd:attribute name="height" type="xsd:double" use="optional"/>
  <xsd:attribute name="maxval" type="xsd:double" use="optional"/>
  <xsd:attribute name="minval" type="xsd:double" use="optional"/>  
 </xsd:complexType>

 <xsd:complexType name="DumbFileWriterType">
  <xsd:sequence>
   <xsd:element name="sink" minOccurs="0" maxOccurs="unbounded">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="source" minOccurs="0" maxOccurs="unbounded">
       <xsd:complexType>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
	<xsd:attribute name="group" type="xsd:string" use="required"/>
       </xsd:complexType>
      </xsd:element>
     </xsd:sequence>
     <xsd:attribute name="name" type="xsd:string" use="required"/>
     <xsd:attribute name="url" type="xsd:string" use="required"/>
    </xsd:complexType>
   </xsd:element>
  </xsd:sequence> 
  <xsd:attribute name="name" type="xsd:string" use="required"/> 
 </xsd:complexType>
  
 <xsd:complexType name="KludgeConfig">
  <xsd:all>
   <xsd:element name="kludgeSources" minOccurs="1" maxOccurs="1">
    <xsd:complexType>
     <xsd:choice minOccurs="0" maxOccurs="unbounded">
      <xsd:element name="kludgeFGen" type="KludgeFGenType"/>
      <xsd:element name="expertDaq" type="ExpertDaqType"/>
      <xsd:element name="dumbFileReplayer" type="DumbFileReplayerType"/>
     </xsd:choice>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="kludgeSinks" minOccurs="1" maxOccurs="1">
    <xsd:complexType>
     <xsd:choice minOccurs="0" maxOccurs="unbounded">
      <xsd:element name="kludgeIMap" type="KludgeIMapType"/>
      <xsd:element name="dumbFileWriter" type="DumbFileWriterType"/>
     </xsd:choice>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="kludgeGUI" minOccurs="1" maxOccurs="1">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="providesSinkGroup" minOccurs="0" maxOccurs="unbounded">
       <xsd:complexType>
        <xsd:attribute name="name" type="xsd:string"/>
       </xsd:complexType>
      </xsd:element>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
  </xsd:all>
 </xsd:complexType>
</xsd:schema>

=== BackupTheBerlios/kludge-svn/trunk/examples/t1.xml
<?xml version="1.0" encoding="UTF-8"?>
<kludgeApp xmlns="http://kludge.berlios.de/v1/kludge" 
	   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://kludge.berlios.de/v1/kludge kludge.xsd">  
 <kludgeSources>	   
  <kludgeFGen name="Gen1">
   <source name="Gen1a" type="sine" freq="0.25" phase="0"/>
   <source name="Gen1b" type="sine" freq="0.1" phase="0.25"/>
  </kludgeFGen>
  <kludgeFGen name="Gen2">
   <source name="Gen2a" />
   <source name="Gen2b" />
  </kludgeFGen>
 </kludgeSources>
 <kludgeSinks>
  <kludgeIMap name="Frame1" colormap="JET" minval="-1" x="40" y="50">
   <sink name="d1" x="5.0" y="5.0" >
    <source name="Gen1a" group="Gen1"/>
   </sink>
   <sink name="d2" x="50.0" y="50.0" >
    <source name="Gen1b" group="Gen1"/>
   </sink>
   <sink name="d3" x="100.0" y="100.0" >
    <source name="Gen2a" group="Gen2"/>
   </sink>
   <image url="file:/root/owork/dlog/kludge/anja02.jpg">
    0000
   </image>
  </kludgeIMap>
  <dumbFileWriter name="log1">
   <sink name="x1" url="file:/root/owork/dlog/kludge/try1.dat">
    <source name="Gen1a" group="Gen1"/>
    <source name="Gen1b" group="Gen1"/>
    <source name="Gen2a" group="Gen2"/>
   </sink>  
  </dumbFileWriter>
 </kludgeSinks>
 <kludgeGUI>
  <providesSinkGroup name="Frame1"/>
 </kludgeGUI>
</kludgeApp>

=== BackupTheBerlios/kludge-svn/trunk/examples/t1r.xml
<?xml version="1.0" encoding="UTF-8"?>
<kludgeApp xmlns="http://kludge.berlios.de/v1/kludge" 
	   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://kludge.berlios.de/v1/kludge kludge.xsd">  
 <kludgeSources>	   
  <dumbFileReplayer name="Gen1" url="file:/root/kludge/kludge/examples/try1s.dat">
   <source name="Gen1a" data_group="Gen1" data_source="Gen1a" autorepeat="true" />
   <source name="Gen1b" data_group="Gen1" data_source="Gen1b" autorepeat="true" />
  </dumbFileReplayer> 
  <dumbFileReplayer name="Gen2" url="file:/root/kludge/kludge/examples/try1s.dat">
   <source name="Gen2a" data_source="Gen2a" data_group="Gen2"/>
   <source name="Gen2b" data_source="Gen2b" data_group="Gen2"/>
  </dumbFileReplayer>
 </kludgeSources>
 <kludgeSinks>
  <kludgeIMap name="Frame1" colormap="JET" minval="-1" x="40" y="50">
   <sink name="d1" x="5.0" y="5.0" >
    <source name="Gen1a" group="Gen1"/>
   </sink>
   <sink name="d2" x="50.0" y="50.0" >
    <source name="Gen1b" group="Gen1"/>
   </sink>
   <sink name="d3" x="100.0" y="100.0" >
    <source name="Gen2a" group="Gen2"/>
   </sink>
   <image url="file:/root/kludge/kludge/examples/anja02.jpg">
    0000
   </image>
  </kludgeIMap>
 </kludgeSinks>
 <kludgeGUI>
  <providesSinkGroup name="Frame1"/>
 </kludgeGUI>
</kludgeApp>

=== BackupTheBerlios/kludge-svn/trunk/examples/motor.xml
<?xml version="1.0" encoding="UTF-8"?>
<kludgeApp xmlns="http://kludge.berlios.de/v1/kludge" 
	   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://kludge.berlios.de/v1/kludge kludge.xsd">  
 <kludgeSources>	   
  <expertDaq name="Chain1" device="/dev/ttyUSB0" baudrate="38400">
   <source name="T01" address="01">
    <sink name="l010" group="Frame1"/>
    <sink name="l011" group="Frame1"/>
    <sink name="l012" group="Frame1"/>
    <sink name="l013" group="Frame1"/>
    <sink name="l014" group="Frame1"/>
    <sink name="l015" group="Frame1"/>
    <sink name="l016" group="Frame1"/>
    <sink name="l017" group="Frame1"/>
   </source>
   <source name="T02" address="02">
    <sink name="l020" group="Frame1"/>
    <sink name="l021" group="Frame1"/>
    <sink name="l022" group="Frame1"/>
    <sink name="l023" group="Frame1"/>
    <sink name="l024" group="Frame1"/>
    <sink name="l025" group="Frame1"/>
    <sink name="l026" group="Frame1"/>
    <sink name="l027" group="Frame1"/>
   </source>   
   <source name="T03" address="03">
    <sink name="l030" group="Frame1"/>
    <sink name="l031" group="Frame1"/>
    <sink name="l032" group="Frame1"/>
    <sink name="l033" group="Frame1"/>
    <sink name="l034" group="Frame1"/>
    <sink name="l035" group="Frame1"/>
    <sink name="l036" group="Frame1"/>
    <sink name="l037" group="Frame1"/>
   </source>
   <source name="T04" address="04">
    <sink name="l040" group="Frame1"/>
    <sink name="l041" group="Frame1"/>
    <sink name="l042" group="Frame1"/>
    <sink name="l043" group="Frame1"/>
    <sink name="l044" group="Frame1"/>
    <sink name="l045" group="Frame1"/>
    <sink name="l046" group="Frame1"/>
    <sink name="l047" group="Frame1"/>
   </source>   
   <source name="T05" address="05">
    <sink name="l050" group="Frame1"/>
    <sink name="l051" group="Frame1"/>
    <sink name="l052" group="Frame1"/>
    <sink name="l053" group="Frame1"/>
    <sink name="l054" group="Frame1"/>
    <sink name="l055" group="Frame1"/>
    <sink name="l056" group="Frame1"/>
    <sink name="l057" group="Frame1"/>
   </source>   
  </expertDaq>
 </kludgeSources>
 <kludgeSinks>
  <kludgeIMap name="Frame1" colormap="JET" minval="18" maxval="40" x="40" y="50">
   <!-- Device 01 -->
   <sink name="l010" x="10" y="10"  data_offset="0" />
   <sink name="l011" x="10" y="20"  data_offset="1" />
   <sink name="l012" x="10" y="30"  data_offset="2" />
   <sink name="l013" x="10" y="40"  data_offset="3" />
   <sink name="l014" x="10" y="50"  data_offset="4" />
   <sink name="l015" x="10" y="60"  data_offset="5" />
   <sink name="l016" x="10" y="70"  data_offset="6" />
   <sink name="l017" x="10" y="80"  data_offset="7" />
   <!-- Device 02 -->
   <sink name="l020" x="30" y="30"  data_offset="0" />
   <sink name="l021" x="30" y="40"  data_offset="1" />
   <sink name="l022" x="30" y="50"  data_offset="2" />
   <sink name="l023" x="30" y="60"  data_offset="3" />
   <sink name="l024" x="30" y="70"  data_offset="4" />
   <sink name="l025" x="30" y="80"  data_offset="5" />
   <sink name="l026" x="30" y="90"  data_offset="6" />
   <sink name="l027" x="30" y="100"  data_offset="7" />
   <!-- Device 03 -->
   <sink name="l030" x="50" y="50"  data_offset="0" />
   <sink name="l031" x="50" y="60"  data_offset="1" />
   <sink name="l032" x="50" y="70"  data_offset="2" />
   <sink name="l033" x="50" y="80"  data_offset="3" />
   <sink name="l034" x="50" y="90"  data_offset="4" />
   <sink name="l035" x="50" y="100"  data_offset="5" />
   <sink name="l036" x="50" y="110"  data_offset="6" />
   <sink name="l037" x="50" y="120"  data_offset="7" />
   <!-- Device 04 -->
   <sink name="l040" x="70" y="70"  data_offset="0" />
   <sink name="l041" x="70" y="80"  data_offset="1" />
   <sink name="l042" x="70" y="90"  data_offset="2" />
   <sink name="l043" x="70" y="100"  data_offset="3" />
   <sink name="l044" x="70" y="110"  data_offset="4" />
   <sink name="l045" x="70" y="120"  data_offset="5" />
   <sink name="l046" x="70" y="130"  data_offset="6" />
   <sink name="l047" x="70" y="140"  data_offset="7" />
   <!-- Device 05 -->
   <sink name="l050" x="90" y="90"  data_offset="0" />
   <sink name="l051" x="90" y="100"  data_offset="1" />
   <sink name="l052" x="90" y="110"  data_offset="2" />
   <sink name="l053" x="90" y="120"  data_offset="3" />
   <sink name="l054" x="90" y="130"  data_offset="4" />
   <sink name="l055" x="90" y="140"  data_offset="5" />
   <sink name="l056" x="90" y="150"  data_offset="6" />
   <sink name="l057" x="90" y="160"  data_offset="7" />
   <image url="file:/root/owork/dlog/kludge/anja02.jpg">
    0000
   </image>
  </kludgeIMap>
 </kludgeSinks>
 <kludgeGUI>
  <providesSinkGroup name="Frame1"/>
 </kludgeGUI>
</kludgeApp>
